
spring:
  application:
    name: fireinfo_healthcheck

  datasource:
    url: jdbc:mysql://43.241.214.218:6033/firedb
    username: firefighting
    password: firefighting
    driver-class-name: com.mysql.jdbc.Driver

  activemq:
    broker-url: tcp://101.236.44.31:61616
    user: admin
    password: )OKM(ijn
    in-memory: true

  jms:
    pub-sub-domain: true

  mail:
    host: smtp.163.com
    username: m15821998331@163.com
    password: usa911
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
    port: 25

  thymeleaf:
    cache: false


#虚拟网关IP、端口和传输内容
firevgw:
  serviceHost: 101.236.42.190
  port: 12346
  message: currentMode

#数据库
mysql:
  sql: SELECT username FROM userinfo WHERE username = 'admin'
  expectResult: admin

#web服务器
web:
  requestUrl: http://101.236.44.31:8080/fireinfo/user/login.do

#mq服务器
mq:
  topicName: fireinfohealthcheck
  message:  ActiveMQ service is health!

#接收邮箱
mail:
  username: 745729377@qq.com

#应用端口
server:
  port: 8090

#服务器平台
service:
  name: 美团云各服务器运行状态


