
spring:
  application:
    name: fireinfo_healthcheck

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/firedb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: true

  jms:
    pub-sub-domain: true

  mail:
    host: smtp.163.com
    username: m15821998331@163.com
    password: usa911
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
    port: 25


#虚拟网关IP、端口和传输内容
firevgw:
  serviceHost: 127.0.0.1
  port: 12346
  message: currentMode

#数据库
mysql:
  sql: SELECT username FROM userinfo WHERE username = 'admin'
  expectResult: admin

#web服务器
web:
  requestUrl: http://127.0.0.1:8080/fireinfo/user/login.do

#mq服务器
mq:
  topicName: fireinfohealthcheck
  message:  ActiveMQ service is health!

#接收邮箱
mail:
  username: 745729377@qq.com

server:
  port: 8090



